### ISSUE TITLE
Drop down menu color not updated

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/ep_font_color#14]
Tested on ehterpad version 1.8.4, Firefox 76 and Win10

## Problem description / steps to reproduce

Select text and color it with a new and different color. Now go to another point in the pad. The color displayed as drop down menu entry stays the same as it was selected before, even if the color where the caret is might be different. 

Drop down color should have changed from blue to black in the example below

![grafik](https://user-images.githubusercontent.com/44228345/82646655-45f2ae80-9c15-11ea-9ef1-69a5c780802a.png)

## Possible solution

The color shown in the drop down menu should show the respective color dependent on the text color where the caret is placed. Implementation could be done as in ep_headings2. There the respective style appears in the menu dependent on the caret.

**Comment by JohnMcLear** [comment]
I implemented this on headings2 plugin, you wanna copy paste the code and submit a pr?

**Comment by Oremountainflorian** [comment]
@techware01 should be possible what do you think?

**Comment by JohnMcLear** [comment]
Afaik I implemented on font type too?

**Comment by Oremountainflorian** [comment]
Any news on that issue? 

@JohnMcLear, do you know a public instance of Etherpad which uses ep_font_type to test if you implemented it? Thanks in advance

**Comment by JohnMcLear** [comment]
Refer to https://github.com/ether/ep_font_family/blob/master/static/js/index.js#L60

https://github.com/ether/ep_font_family/blob/master/static/js/index.js#L32 should be able to copy/pasted replacing ``family`` with ``color``

Should be just a case of copy/pasting that logic and making sure the entry is in ``ep.json``.  I'd welcome seeing this as a PR 👍
